# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Natneon/dd70ee068b9f1d83375b14008daf8c50/untitled3.ipynb
"""



"""**Esto va en negrita**

*Esto va en cursiva*
"""





"""![Gatito](https://hidogfb.files.wordpress.com/2015/09/fondo-gatito-1366x768.jpg)"""

import matplotlib.pyplot as plt

plt??

